#!/bin/sh /etc/rc.common

START=99
STOP=99

WAN_INTF=wlan1
LAN_INTF=br-lan
VAR_RUN_IPV6_LAN=/var/run/ipv6.$LAN_INTF

if [ -e $VAR_RUN_IPV6_LAN ] ; then
	LAST_IPV6_LAN=`cat $VAR_RUN_IPV6_LAN`
else
	LAST_IPV6_LAN=""
fi

IPV6_PREFIX=`ip -6 addr show dev $WAN_INTF | grep global | awk 'BEGIN { FS = " " } { print $2 }' | awk 'BEGIN { FS = "/" } { print $1 }' | grep 2001: | awk 'BEGIN { FS = ":" } { print $1  ":" $2 ":" $3 ":" $4 }'`
TARGET_LAN_IPV6_ADDRESS=$IPV6_PREFIX:8000::1

start() {
	# Check if target LAN IPv6 address already set
	ip -6 addr show dev $LAN_INTF | grep global | awk 'BEGIN { FS = " " } { print $2 }' | awk 'BEGIN { FS = "/" } { print $1 }' | grep $TARGET_LAN_IPV6_ADDRESS > /dev/null

	LAN_IPV6_SET=$?

	if [ $LAN_IPV6_SET -eq 0 ] ; then
		echo $TARGET_LAN_IPV6_ADDRESS already set
	else
		echo $TARGET_LAN_IPV6_ADDRESS not set yet
		ip -6 addr add $TARGET_LAN_IPV6_ADDRESS/65 dev $LAN_INTF
		echo $TARGET_LAN_IPV6_ADDRESS > $VAR_RUN_IPV6_LAN

	fi

	if [ "$LAST_IPV6_LAN" != "" -a "$TARGET_LAN_IPV6_ADDRESS" != "$LAST_IPV6_LAN" ] ; then
		ip -6 addr del $LAST_IPV6_LAN dev $LAN_INTF
	fi
}

stop() {
	ip -6 addr del $TARGET_LAN_IPV6_ADDRESS/65 dev $LAN_INTF
}

restart() {
	stop "$@"
	start "$@"
}
