#!/bin/sh

. /etc/ipv6.conf

IP6IP6_COUNT=`ifconfig | grep $TUNNEL_DEV | wc -l`

if [ $IP6IP6_COUNT -gt 0 ]; then
    echo "IPv6 in IPv6 tunnel already exists."
    exit 0
fi

ip -6 route add $SERVER dev $ROUTE_DEV
ip -6 tunnel add $TUNNEL_DEV mode $TUNNEL_DEV remote $SERVER local $CLIENT dev $ROUTE_DEV
ip -6 addr add $TUNNEL_IPV6 dev $TUNNEL_DEV
ip link set dev $TUNNEL_DEV up
ip -6 route add default dev $TUNNEL_DEV
ip -6 route del default dev $ROUTE_DEV

