#!/bin/bash

# Source function library.
. /etc/rc.d/init.d/functions

export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

start() {
  service postgresql94 start
  service mysqld start
  (cd /root/dynamodb; java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb) >& /var/log/dynamodb.log &
  /redis-stable/src/redis-server >& /var/log/redis.log &
  (cd ~/cloudsrc/manager/build/nodeapp; ./dev-start.sh) >& /var/log/nodeapp.log &
  (cd ~/cloudsrc/manager/build/nodeapp; node ./build/js/deviceAdapterServer-start.js) >& /var/log/da.log &
  (cd ~/cloudsrc/manager/build/nodeapp; node ./build/js/deviceEventManager-start.js) >& /var/log/dev.log &
  (cd ~/cloudsrc/manager/build/nodeapp; node ./build/js/timerDynamoJobs-start.js) >& /var/log/td.log &
  (cd ~/cloudsrc/manager/build/nodeapp; node ./build/js/timerjobs-start.js) >& /var/log/tj.log &
  (cd ~/cloudsrc/manager/build/nodeapp; node ./tools/simulator.js device.csv wss://localhost:8443) >& /var/log/sim.log &
  (cd ~/cloudsrc; ./license-server/src/bin/www) >& /var/log/ls.log &
}

stop(){
  service postgresql94 stop
  service mysqld stop
  killall node
}

reload(){
  stop
  start
}

initdb(){
  createdb -h localhost -p 5432 -U postgres cloudmgr_test_db
  (cd ~/cloudsrc/manager/build/nodeapp; node tools/postgres/index.js)
  (cd ~/cloudsrc/manager/build/nodeapp; psql -h localhost -U postgres -d cloudmgr_test_db -a -f ./tools/postgres/sql/initData.sql)
  mysql < /root/cloudsrc/license-server/src/mysql/sql/create_database_and_user.sql
  mysql license < /root/cloudsrc/license-server/src/mysql/sql/license_schema_empty.sql
  mysql license < /root/cloudsrc/license-server/src/mysql/sql/license_procedure.sql
  mysql license < /root/cloudsrc/license-server/src/mysql/sql/license_schema_initial_data.sql
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status -p "$pidfile" postmaster
        script_result=$?
        ;;
  restart)
        restart
        ;;
  condrestart|try-restart)
        condrestart
        ;;
  reload)
        reload
        ;;
  force-reload)
        restart
        ;;
  initdb)
        initdb
        ;;
  *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload|initdb|upgrade}"
        exit 2
esac