#!/bin/bash

source /etc/ipv6.conf

function start {
  ip tunnel add he-ipv6 mode sit remote $SERVER_IP ttl 255
  ip link set he-ipv6 up
  ip addr add $CLIENT_IPV6 dev he-ipv6
  ip -6 route add default dev he-ipv6
  ip -f inet6 addr
}

function stop {
  ip -6 route del default dev he-ipv6
  ip tunnel del he-ipv6
}

$1

